### PR TITLE
Incorporate UFLConstraints into Firedrake

### PR DESCRIPTION
**Pull request by medinaeder**
This PR should resolved issue #44 

The code has not been tested in the fenics environment. If someone could please verify that this does not break any functionality on that side that would be great.

### CODE REVIEW

**Comment by sebastkm** [comment]
Thanks for the pull request.

The intention with pyadjoint is to be a generic framework for AD, and so it does not have a concept of a `backend` or UFL.
Moving `UFLConstraint` to `dolfin_adjoint_common` would be more suitable as this is where code that is shared between the fenics and firedrake implementations live.

**Comment by medinaeder** [comment]
Sounds good. I have relocated the files.
Still seems to work.

**Comment by sebastkm** [comment]
Nice. Could you also remove the UFL constraints file from `fenics_adjoint` and add a similar `__init__.py` import for `fenics_adjoint` using `dolfin_adjoint_common`?

**Comment by sebastkm** [comment]
This looks good to me now.

**Comment by medinaeder** [comment]
Great! Thanks for cleaning it up.

**Review by sebastkm — APPROVED** [review]

**Pull request merged**
