### PR TITLE
Block tagging

### PR DESCRIPTION
**Pull request by jwallwork23**
I find this useful for sorting between different solve blocks written to tape when solving systems of equations.

### CODE REVIEW

**Comment by sebastkm** [comment]
Making it easier to differentiate between solves would be nice, indeed.

I wonder if perhaps it would be better with a more general pyadjoint approach, perhaps an optional argument to all annotated functions such as `ad_block_tag` which populates some `Block.tag` attribute.
Assuming the `options_prefix` attribute is not going to be used for anything inside the solve blocks.
This approach could also be complimented with some tape functions that return a list of blocks with a specific tag.

**Comment by jwallwork23** [comment]
Good idea! I'll have a go at implementing something along those lines.

**Comment by jwallwork23** [comment]
See also [Firedrake PR](https://github.com/firedrakeproject/firedrake/pull/2174).

**Comment by jwallwork23** [comment]
@sebastkm What do you think of this approach? The Firedrake tests that fail here pass on my Firedrake PR (which tests against the pyadjoint branch here).

**Comment by jwallwork23** [comment]
Thanks! Okay, great. I'll get someone to look at the corresponding Firedrake PR and then get them both merged together.

**Pull request merged**
